# https://cloud.google.com/appengine/docs/flexible/go/configuring-your-app-with-app-yaml
runtime: custom
env: flex
service: landskape

env_variables:
  # must be set
  API_KEY: dev

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10